import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  pt: {
    'nav.home': 'Home',
    'nav.listings': 'Hospedagens',
    'nav.about': 'Sobre',
    'nav.contact': 'Contato',
    'nav.favorites': 'Favoritos',
    'nav.reserve': 'RESERVAR',
    'nav.language': 'Idioma',
    'hero.title': 'Dê valor ao seu tempo, Nós cuidamos do resto!',
    'search.where': 'Onde?',
    'search.placeholder': 'Bairro, rua ou nome...',
    'search.checkin': 'Check-in',
    'search.checkout': 'Check-out',
    'search.guests': 'Hóspedes',
    'search.button': 'PESQUISAR AGORA',
    'search.update': 'ATUALIZAR',
    'home.featured.tag': 'Opções Selecionadas',
    'home.featured.title': 'Diversas Opções de Lofts',
    'home.featured.desc': 'As hospedagens mais procuradas pelos expositores e visitantes do São Paulo Expo.',
    'home.featured.all': 'Ver todas as 80 hospedagens',
    'home.about.tag': 'Qualidade Spexpo Lofts',
    'home.about.title': 'Conforto que te aproxima do sucesso.',
    'home.about.desc': 'Gerenciamos hospedagens estrategicamente localizadas na região da Vila Guarani e Jabaquara, focando em oferecer o conforto de casa com a eficiência de um hotel.',
    'home.about.checkin': 'Check-in Ágil',
    'home.about.checkin.desc': 'Processo eletrônico e seguro via senha ou concierge dedicado.',
    'home.about.wifi': 'Wi-Fi Premium',
    'home.about.wifi.desc': 'Conexão dedicada de alta velocidade em todas as nossas unidades.',
    'home.about.button': 'CONHEÇA NOSSA HISTÓRIA',
    'home.gallery.tag': 'Experiência Visual',
    'home.gallery.title': 'Galeria Spexpo',
    'home.cta.title': 'Pronto para reservar?',
    'home.cta.desc': 'Garanta o melhor preço reservando diretamente em nosso marketplace exclusivo para o São Paulo Expo.',
    'home.cta.availability': 'VER DISPONIBILIDADE',
    'home.cta.whatsapp': 'FALAR NO WHATSAPP',
    'prop.guests': 'Hóspedes',
    'prop.bedrooms': 'Quartos',
    'prop.bathrooms': 'Banheiros',
    'prop.area': 'Área',
    'prop.desc': 'Descrição da Hospedagem',
    'prop.amenities': 'Comodidades e Facilidades',
    'prop.location': 'Localização Privilegiada',
    'prop.price_from': 'Diárias a partir de',
    'prop.night': 'noite',
    'prop.reserve': 'RESERVAR AGORA',
    'prop.summary': 'Resumo',
    'prop.nights': 'noites',
    'prop.total': 'Total',
    'prop.adults': 'Adultos',
    'prop.children': 'Crianças',
    'prop.similar': 'Explore similares',
    'about.title': 'Sobre Nós',
    'about.subtitle': 'Especialistas em hospitalidade para eventos e exposições.',
    'about.admin': 'Administrador Sênior',
    'about.exp': 'Experiência e Gestão',
    'about.desc1': 'Raul Cavalcante lidera a SPEXPO LOFTS há sete anos, unindo tecnologia e administração para oferecer o melhor em estadias de curta temporada.',
    'about.desc2': 'Com formação em TI e MBA em Administração, Raul aplicou 11 anos de expertise no Banco Itaú para profissionalizar a gestão de acomodações na Vila Guarani e Jabaquara, garantindo um padrão hoteleiro em lofts modernos.',
    'about.standard': 'Padrão Elite',
    'about.standard.desc': 'Cada loft é preparado com enxoval de alta gramatura e limpeza rigorosa.',
    'about.service': 'Atendimento',
    'about.service.desc': 'Suporte 24h dedicado exclusivamente aos hóspedes Spexpo.',
    'contact.title': 'Fale Conosco',
    'contact.subtitle': 'Estamos prontos para atender você. Entre em contato para dúvidas, reservas ou parcerias.',
    'contact.channels': 'Canais de Atendimento',
    'contact.desc': 'Prefere um atendimento rápido? Chame nossa equipe no WhatsApp ou ligue diretamente.',
    'contact.hours': 'Horário de Atendimento',
    'contact.hours.detail': 'Segunda a Sexta: 09h às 18h\nSábados: 09h às 13h',
    'contact.loc': 'Nossa Localização',
    'contact.loc.detail': 'Rua Maringá, 106 - Vila Guarani\nSão Paulo - SP, 04311-000\n(Próximo ao Metrô Jabaquara e SP Expo)',
    'fav.title': 'Meus Favoritos',
    'fav.subtitle': 'Gerencie as hospedagens que você mais gostou.',
    'fav.empty': 'Você ainda não tem favoritos',
    'fav.empty.desc': 'Navegue pelas nossas hospedagens e clique no coração para salvar aquelas que você mais gostar.',
    'fav.explore': 'Explorar Hospedagens',
    'footer.desc': 'Especialistas em locação de curta temporada para expositores do São Paulo Expo. Conforto, proximidade e excelência.',
    'footer.nav': 'Navegação',
    'footer.contact': 'Contato',
    'footer.loc': 'Localização'
  },
  en: {
    'nav.home': 'Home',
    'nav.listings': 'Accommodations',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.favorites': 'Favorites',
    'nav.reserve': 'BOOK NOW',
    'nav.language': 'Language',
    'hero.title': 'Value your time, We take care of the rest!',
    'search.where': 'Where?',
    'search.placeholder': 'Neighborhood, street or name...',
    'search.checkin': 'Check-in',
    'search.checkout': 'Check-out',
    'search.guests': 'Guests',
    'search.button': 'SEARCH NOW',
    'search.update': 'UPDATE',
    'home.featured.tag': 'Selected Options',
    'home.featured.title': 'Diverse Loft Options',
    'home.featured.desc': 'The most sought-after accommodations by exhibitors and visitors of São Paulo Expo.',
    'home.featured.all': 'See all 80 accommodations',
    'home.about.tag': 'Spexpo Lofts Quality',
    'home.about.title': 'Comfort that brings you closer to success.',
    'home.about.desc': 'We manage strategically located accommodations in the Vila Guarani and Jabaquara region, focusing on offering the comfort of home with the efficiency of a hotel.',
    'home.about.checkin': 'Agile Check-in',
    'home.about.checkin.desc': 'Electronic and secure process via password or dedicated concierge.',
    'home.about.wifi': 'Premium Wi-Fi',
    'home.about.wifi.desc': 'Dedicated high-speed connection in all our units.',
    'home.about.button': 'DISCOVER OUR STORY',
    'home.gallery.tag': 'Visual Experience',
    'home.gallery.title': 'Spexpo Gallery',
    'home.cta.title': 'Ready to book?',
    'home.cta.desc': 'Guarantee the best price by booking directly in our exclusive marketplace for São Paulo Expo.',
    'home.cta.availability': 'CHECK AVAILABILITY',
    'home.cta.whatsapp': 'TALK ON WHATSAPP',
    'prop.guests': 'Guests',
    'prop.bedrooms': 'Bedrooms',
    'prop.bathrooms': 'Bathrooms',
    'prop.area': 'Area',
    'prop.desc': 'Accommodation Description',
    'prop.amenities': 'Amenities and Facilities',
    'prop.location': 'Prime Location',
    'prop.price_from': 'Rates starting at',
    'prop.night': 'night',
    'prop.reserve': 'BOOK NOW',
    'prop.summary': 'Summary',
    'prop.nights': 'nights',
    'prop.total': 'Total',
    'prop.adults': 'Adults',
    'prop.children': 'Children',
    'prop.similar': 'Explore similar ones',
    'about.title': 'About Us',
    'about.subtitle': 'Specialists in hospitality for events and exhibitions.',
    'about.admin': 'Senior Manager',
    'about.exp': 'Experience and Management',
    'about.desc1': 'Raul Cavalcante has led SPEXPO LOFTS for seven years, combining technology and administration to offer the best in short-term stays.',
    'about.desc2': 'With a degree in IT and an MBA in Administration, Raul applied 11 years of expertise at Banco Itaú to professionalize the management of accommodations in Vila Guarani and Jabaquara, ensuring a hotel standard in modern lofts.',
    'about.standard': 'Elite Standard',
    'about.standard.desc': 'Each loft is prepared with high-weight linen and rigorous cleaning.',
    'about.service': 'Customer Service',
    'about.service.desc': '24h support dedicated exclusively to Spexpo guests.',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are ready to assist you. Get in touch for questions, bookings or partnerships.',
    'contact.channels': 'Service Channels',
    'contact.desc': 'Prefer quick service? Call our team on WhatsApp or call directly.',
    'contact.hours': 'Opening Hours',
    'contact.hours.detail': 'Monday to Friday: 09h to 18h\nSaturdays: 09h to 13h',
    'contact.loc': 'Our Location',
    'contact.loc.detail': 'Rua Maringá, 106 - Vila Guarani\nSão Paulo - SP, 04311-000\n(Close to Jabaquara Metro and SP Expo)',
    'fav.title': 'My Favorites',
    'fav.subtitle': 'Manage the accommodations you liked most.',
    'fav.empty': 'You have no favorites yet',
    'fav.empty.desc': 'Browse our accommodations and click on the heart to save the ones you like best.',
    'fav.explore': 'Explore Accommodations',
    'footer.desc': 'Short-term rental specialists for exhibitors at São Paulo Expo. Comfort, proximity and excellence.',
    'footer.nav': 'Navigation',
    'footer.contact': 'Contact',
    'footer.loc': 'Location'
  },
  es: {
    'nav.home': 'Inicio',
    'nav.listings': 'Alojamientos',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.favorites': 'Favoritos',
    'nav.reserve': 'RESERVAR',
    'nav.language': 'Idioma',
    'hero.title': '¡Valora tu tiempo, nosotros nos encargamos del resto!',
    'search.where': '¿Dónde?',
    'search.placeholder': 'Barrio, calle o nombre...',
    'search.checkin': 'Check-in',
    'search.checkout': 'Check-out',
    'search.guests': 'Huéspedes',
    'search.button': 'BUSCAR AHORA',
    'search.update': 'ACTUALIZAR',
    'home.featured.tag': 'Opciones Seleccionadas',
    'home.featured.title': 'Diversas Opciones de Lofts',
    'home.featured.desc': 'Los alojamientos más buscados por expositores y visitantes de São Paulo Expo.',
    'home.featured.all': 'Ver los 80 alojamientos',
    'home.about.tag': 'Calidad Spexpo Lofts',
    'home.about.title': 'Confort que te acerca al éxito.',
    'home.about.desc': 'Gestionamos alojamientos estratégicamente ubicados en la região de Vila Guarani y Jabaquara, enfocándonos en ofrecer el confort del hogar con la eficiencia de un hotel.',
    'home.about.checkin': 'Check-in Ágil',
    'home.about.checkin.desc': 'Proceso electrónico y seguro mediante contraseña o conserje dedicado.',
    'home.about.wifi': 'Wi-Fi Premium',
    'home.about.wifi.desc': 'Conexión dedicada de alta velocidad em todas nuestras unidades.',
    'home.about.button': 'CONOZCA NUESTRA HISTORIA',
    'home.gallery.tag': 'Experiencia Visual',
    'home.gallery.title': 'Galería Spexpo',
    'home.cta.title': '¿Listo para reservar?',
    'home.cta.desc': 'Garantice el mejor precio reservando directamente en nuestro marketplace exclusivo para São Paulo Expo.',
    'home.cta.availability': 'VER DISPONIBILIDAD',
    'home.cta.whatsapp': 'HABLAR POR WHATSAPP',
    'prop.guests': 'Huéspedes',
    'prop.bedrooms': 'Habitaciones',
    'prop.bathrooms': 'Baños',
    'prop.area': 'Área',
    'prop.desc': 'Descripción del Alojamiento',
    'prop.amenities': 'Comodidades y Facilidades',
    'prop.location': 'Ubicación Privilegiada',
    'prop.price_from': 'Tarifas desde',
    'prop.night': 'noche',
    'prop.reserve': 'RESERVAR AHORA',
    'prop.summary': 'Resumen',
    'prop.nights': 'noches',
    'prop.total': 'Total',
    'prop.adults': 'Adultos',
    'prop.children': 'Niños',
    'prop.similar': 'Explore similares',
    'about.title': 'Nosotros',
    'about.subtitle': 'Especialistas en hospitalidad para eventos y exposiciones.',
    'about.admin': 'Administrador Senior',
    'about.exp': 'Experiencia y Gestión',
    'about.desc1': 'Raul Cavalcante lidera SPEXPO LOFTS desde hace siete años, uniendo tecnología y administración para ofrecer lo mejor en estadías de corta temporada.',
    'about.desc2': 'Con formación en TI y un MBA en Administración, Raul aplicó 11 años de experiencia en el Banco Itaú para profesionalizar la gestión de alojamientos en Vila Guarani y Jabaquara, garantizando un estándar hotelero en lofts modernos.',
    'about.standard': 'Estándar Elite',
    'about.standard.desc': 'Cada loft está preparado con lencería de alto gramaje y limpieza rigurosa.',
    'about.service': 'Atención al Cliente',
    'about.service.desc': 'Soporte 24h dedicado exclusivamente a los huéspedes de Spexpo.',
    'contact.title': 'Contáctenos',
    'contact.subtitle': 'Estamos listos para atenderte. Contáctanos para dudas, reservas o alianzas.',
    'contact.channels': 'Canales de Atención',
    'contact.desc': '¿Prefieres un servicio rápido? Llama a nuestro equipo por WhatsApp o llama directamente.',
    'contact.hours': 'Horario de Atención',
    'contact.hours.detail': 'Lunes a Viernes: 09h a 18h\nSábados: 09h a 13h',
    'contact.loc': 'Nuestra Ubicación',
    'contact.loc.detail': 'Rua Maringá, 106 - Vila Guarani\nSão Paulo - SP, 04311-000\n(Cerca del Metro Jabaquara y SP Expo)',
    'fav.title': 'Mis Favoritos',
    'fav.subtitle': 'Gestiona los alojamientos que más te gustaron.',
    'fav.empty': 'Aún no tienes favoritos',
    'fav.empty.desc': 'Navega por nuestros alojamientos y haz clic en el corazón para guardar los que más te gusten.',
    'fav.explore': 'Explorar Alojamientos',
    'footer.desc': 'Especialistas en alquileres a corto plazo para expositores en São Paulo Expo. Confort, cercanía y excelencia.',
    'footer.nav': 'Navegación',
    'footer.contact': 'Contacto',
    'footer.loc': 'Ubicación'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('pt');

  useEffect(() => {
    const saved = localStorage.getItem('spexpo_lang') as Language;
    if (saved && ['pt', 'en', 'es'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('spexpo_lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};